/* Tabla de cadenas ES/EN propia de Aura UI.
 *
 * Independiente del sistema de idiomas (.lang) de Rockbox: Aura no
 * reutiliza ninguna cadena de la UI que reemplaza, asi que mantiene su
 * propia tabla, pequena y completa, en vez de generar un .lang nuevo
 * para un puñado de textos. Ver D-013 en DECISIONS.md.
 */
#ifndef AURA_LANG_H
#define AURA_LANG_H

typedef enum {
    AURA_STR_MUSIC = 0,
    AURA_STR_VIDEOS,
    AURA_STR_PHOTOS,
    AURA_STR_NOWPLAYING,
    AURA_STR_SETTINGS,

    AURA_STR_SETTINGS_THEME,
    AURA_STR_SETTINGS_ANIMATIONS,
    AURA_STR_SETTINGS_GRAPHICS,
    AURA_STR_SETTINGS_EQ,
    AURA_STR_SETTINGS_BRIGHTNESS,
    AURA_STR_SETTINGS_LANGUAGE,
    AURA_STR_SETTINGS_ABOUT,
    AURA_STR_SETTINGS_SHUFFLE,
    AURA_STR_SETTINGS_REPEAT,

    AURA_STR_REPEAT_OFF,
    AURA_STR_REPEAT_ALL,
    AURA_STR_REPEAT_ONE,

    AURA_STR_SETTINGS_BACKLIGHT,
    AURA_STR_SETTINGS_SLEEPTIMER,
    AURA_STR_SETTINGS_VOLUME_LIMIT,
    AURA_STR_SETTINGS_CLICKER,
    AURA_STR_SETTINGS_MAINMENU,
    AURA_STR_SETTINGS_RESET,

    AURA_STR_TIMEOUT_OFF,
    AURA_STR_TIMEOUT_ALWAYS,

    AURA_STR_MAINMENU_RESTORE,

    AURA_STR_RESET_CONFIRM_TITLE,
    AURA_STR_RESET_CONFIRM_BODY,
    AURA_STR_RESET_DONE,

    AURA_STR_THEME_LIGHT,
    AURA_STR_THEME_DARK,

    AURA_STR_ANIM_NONE,
    AURA_STR_ANIM_MINIMAL,
    AURA_STR_ANIM_ALL,

    AURA_STR_GFX_NONE,
    AURA_STR_GFX_MINIMAL,
    AURA_STR_GFX_ALL,

    AURA_STR_EQ_FLAT,
    AURA_STR_EQ_BASS_BOOST,
    AURA_STR_EQ_VOCAL,
    AURA_STR_EQ_TREBLE_BOOST,

    AURA_STR_LANG_ES,
    AURA_STR_LANG_EN,

    AURA_STR_ABOUT_BUILT_ON,
    AURA_STR_ABOUT_MUSIC,
    AURA_STR_ABOUT_VIDEOS,
    AURA_STR_ABOUT_PHOTOS,
    AURA_STR_ABOUT_PLAYLISTS,
    AURA_STR_ABOUT_NO_SYNC,

    AURA_STR_EMPTY_MUSIC,
    AURA_STR_EMPTY_VIDEOS,
    AURA_STR_EMPTY_PHOTOS,
    AURA_STR_NOTHING_PLAYING,

    AURA_STR_MUSIC_ARTISTS,
    AURA_STR_MUSIC_ALBUMS,
    AURA_STR_MUSIC_SONGS,
    AURA_STR_MUSIC_PLAYLISTS,
    AURA_STR_MUSIC_GENRES,
    AURA_STR_DB_NOT_READY,
    AURA_STR_EMPTY_LIST,
    AURA_STR_UNSUPPORTED_FORMAT,

    AURA_STR_YES,
    AURA_STR_NO,

    AURA_STR_PLAYLIST_ADDED,
    AURA_STR_ABOUT_STORAGE,
    AURA_STR_PLAYLIST_PICK,

    /* Acento configurable (PLAN.md T0.3) -- presets provisionales, sin
     * consumidor de UI de swatch todavia (lista de eleccion por texto,
     * mismo patron que Tema/Idioma). */
    AURA_STR_SETTINGS_ACCENT,
    AURA_STR_ACCENT_PINK,
    AURA_STR_ACCENT_RED,
    AURA_STR_ACCENT_ORANGE,
    AURA_STR_ACCENT_GREEN,
    AURA_STR_ACCENT_BLUE,
    AURA_STR_ACCENT_PURPLE,

    AURA_STR_COUNT,
} aura_str_id_t;

/* Devuelve la cadena para el idioma activo (aura_settings.language). */
const char *aura_str(aura_str_id_t id);

#endif /* AURA_LANG_H */
