#include "aura_lang.h"
#include "aura_settings.h"

static const char *const strings_es[AURA_STR_COUNT] = {
    [AURA_STR_MUSIC]              = "Música",
    [AURA_STR_VIDEOS]             = "Videos",
    [AURA_STR_PHOTOS]             = "Fotos",
    [AURA_STR_NOWPLAYING]         = "Ahora suena",
    [AURA_STR_SETTINGS]           = "Ajustes",

    [AURA_STR_SETTINGS_THEME]       = "Tema",
    [AURA_STR_SETTINGS_ANIMATIONS]  = "Animaciones",
    [AURA_STR_SETTINGS_GRAPHICS]    = "Gráficos",
    [AURA_STR_SETTINGS_EQ]          = "Ecualizador",
    [AURA_STR_SETTINGS_BRIGHTNESS]  = "Brillo",
    [AURA_STR_SETTINGS_LANGUAGE]    = "Idioma",
    [AURA_STR_SETTINGS_ABOUT]       = "Acerca de",
    [AURA_STR_SETTINGS_SHUFFLE]     = "Aleatorio",
    [AURA_STR_SETTINGS_REPEAT]      = "Repetir",

    [AURA_STR_REPEAT_OFF]           = "Desactivado",
    [AURA_STR_REPEAT_ALL]           = "Todo",
    [AURA_STR_REPEAT_ONE]           = "Uno",

    [AURA_STR_SETTINGS_BACKLIGHT]    = "Temporiz. luz",
    [AURA_STR_SETTINGS_SLEEPTIMER]   = "Temporiz. reposo",
    [AURA_STR_SETTINGS_VOLUME_LIMIT] = "Límite volumen",
    [AURA_STR_SETTINGS_CLICKER]      = "Sonido de clic",
    [AURA_STR_SETTINGS_MAINMENU]     = "Menú principal",
    [AURA_STR_SETTINGS_RESET]        = "Restablecer ajustes",

    [AURA_STR_TIMEOUT_OFF]          = "Desactivado",
    [AURA_STR_TIMEOUT_ALWAYS]       = "Siempre",

    [AURA_STR_MAINMENU_RESTORE]     = "Restaurar menú principal",

    [AURA_STR_RESET_CONFIRM_TITLE]  = "Restablecer ajustes",
    [AURA_STR_RESET_CONFIRM_BODY]   = "Esto vuelve todos los ajustes a su valor de fábrica.",
    [AURA_STR_RESET_DONE]           = "Ajustes restablecidos",

    [AURA_STR_THEME_LIGHT]        = "Claro",
    [AURA_STR_THEME_DARK]         = "Oscuro",

    [AURA_STR_ANIM_NONE]          = "Ninguna",
    [AURA_STR_ANIM_MINIMAL]       = "Mínimas",
    [AURA_STR_ANIM_ALL]           = "Todas",

    [AURA_STR_GFX_NONE]           = "Ninguno",
    [AURA_STR_GFX_MINIMAL]        = "Mínimos",
    [AURA_STR_GFX_ALL]            = "Todos",



    [AURA_STR_LANG_ES]            = "Español",
    [AURA_STR_LANG_EN]            = "Inglés",

    [AURA_STR_ABOUT_BUILT_ON]     = "Basado en Rockbox",
    [AURA_STR_ABOUT_MUSIC]        = "Música",
    [AURA_STR_ABOUT_VIDEOS]       = "Video",
    [AURA_STR_ABOUT_PHOTOS]       = "Fotos",
    [AURA_STR_ABOUT_PLAYLISTS]    = "Listas",
    [AURA_STR_ABOUT_NO_SYNC]      = "Aún no te has sincronizado con Aura Studio.",

    [AURA_STR_EMPTY_MUSIC]        = "Sin música todavía",
    [AURA_STR_EMPTY_VIDEOS]       = "Sin videos todavía",
    [AURA_STR_EMPTY_PHOTOS]       = "Sin fotos todavía",
    [AURA_STR_NOTHING_PLAYING]    = "Nada sonando",

    [AURA_STR_MUSIC_ARTISTS]      = "Artistas",
    [AURA_STR_MUSIC_ALBUMS]       = "Álbumes",
    [AURA_STR_MUSIC_SONGS]        = "Canciones",
    [AURA_STR_MUSIC_PLAYLISTS]    = "Listas",
    [AURA_STR_MUSIC_GENRES]       = "Géneros",
    [AURA_STR_DB_NOT_READY]       = "Preparando la biblioteca…",
    [AURA_STR_EMPTY_LIST]         = "Sin resultados",
    [AURA_STR_UNSUPPORTED_FORMAT] = "Formato no soportado",

    [AURA_STR_YES]                = "Sí",
    [AURA_STR_NO]                 = "No",

    [AURA_STR_ABOUT_STORAGE]      = "Almacenamiento",
    [AURA_STR_PLAYLIST_PICK]      = "Gira la rueda para elegir",

    [AURA_STR_SETTINGS_ACCENT]    = "Color de acento",
    [AURA_STR_ACCENT_PINK]        = "Rosa",
    [AURA_STR_ACCENT_RED]         = "Rojo",
    [AURA_STR_ACCENT_ORANGE]      = "Naranja",
    [AURA_STR_ACCENT_GREEN]       = "Verde",
    [AURA_STR_ACCENT_BLUE]        = "Azul",
    [AURA_STR_ACCENT_PURPLE]      = "Morado",
    [AURA_STR_SETTINGS_LEFT_PANEL_SHADOW] = "Mostrar sombras",
    [AURA_STR_MUSIC_COVERFLOW]    = "Cover Flow",
    [AURA_STR_UNKNOWN_ALBUM]      = "Álbum desconocido",
    [AURA_STR_UNKNOWN_ARTIST]     = "Artista desconocido",
    [AURA_STR_UNKNOWN_GENRE]      = "Género desconocido",
    [AURA_STR_UNKNOWN_TITLE]      = "Sin título",
    [AURA_STR_MUSIC_COMPOSERS]    = "Autores",
    [AURA_STR_MUSIC_COMPILATIONS] = "Recopilaciones",
    [AURA_STR_MUSIC_AUDIOBOOKS]   = "Audiolibros",
    [AURA_STR_MUSIC_SEARCH]       = "Búsqueda",
    [AURA_STR_ALL]                = "Todos",
    [AURA_STR_EXTRAS]             = "Extras",
    [AURA_STR_SHUFFLE_SONGS]      = "Canciones aleat.",
    [AURA_STR_EXTRAS_CLOCKS]      = "Reloj internacional",
    [AURA_STR_EXTRAS_CALENDAR]    = "Calendarios",
    [AURA_STR_EXTRAS_CONTACTS]    = "Agenda",
    [AURA_STR_EXTRAS_ALARMS]      = "Alarmas",
    [AURA_STR_EXTRAS_GAMES]       = "Juegos",
    [AURA_STR_EXTRAS_NOTES]       = "Notas",
    [AURA_STR_SETTINGS_SCREENLOCK] = "Bloqueo de pantalla",
    [AURA_STR_EXTRAS_STOPWATCH]   = "Cronómetro",
    [AURA_STR_EMPTY_GENERIC]      = "No hay nada aquí todavía",
    [AURA_STR_SETTINGS_SHOW_ICONS] = "Mostrar iconos",
    [AURA_STR_EQ_OFF] = "Desactivado",
    [AURA_STR_EQ_ACOUSTIC] = "Acústica",
    [AURA_STR_EQ_BASS_BOOST] = "Amplif. graves",
    [AURA_STR_EQ_BASS_RED] = "Reducir graves",
    [AURA_STR_EQ_CLASSICAL] = "Clásica",
    [AURA_STR_EQ_DANCE] = "Dance",
    [AURA_STR_EQ_DEEP] = "Deep",
    [AURA_STR_EQ_ELECTRONIC] = "Electrónica",
    [AURA_STR_EQ_FLAT] = "Flat",
    [AURA_STR_EQ_HIPHOP] = "Hip Hop",
    [AURA_STR_EQ_JAZZ] = "Jazz",
    [AURA_STR_EQ_LATIN] = "Latina",
    [AURA_STR_EQ_LOUDNESS] = "Loudness",
    [AURA_STR_EQ_LOUNGE] = "Lounge",
    [AURA_STR_EQ_PIANO] = "Piano",
    [AURA_STR_EQ_POP] = "Pop",
    [AURA_STR_EQ_RNB] = "R&B",
    [AURA_STR_EQ_ROCK] = "Rock",
    [AURA_STR_EQ_SMALLSPK] = "Minialtavoces",
    [AURA_STR_EQ_SPOKEN] = "Voz",
    [AURA_STR_EQ_TREBLE_RED] = "Reducir agudos",
    [AURA_STR_EQ_VOCAL_BOOST] = "Aumentar voz",
    [AURA_STR_LANG_DA] = "Dansk",
    [AURA_STR_LANG_DE] = "Deutsch",
    [AURA_STR_LANG_FR] = "Français",
    [AURA_STR_LANG_IT] = "Italiano",
    [AURA_STR_LANG_NL] = "Nederlands",
    [AURA_STR_LANG_NO] = "Norsk",
    [AURA_STR_LANG_PT] = "Português",
    [AURA_STR_LANG_FI] = "Suomi",
    [AURA_STR_LANG_SV] = "Svenska",
    [AURA_STR_LANG_JA] = "日本語",
    [AURA_STR_LANG_ZH] = "中文",
    [AURA_STR_LANG_KO] = "한국어",
    [AURA_STR_LANG_RU] = "Русский",
    [AURA_STR_VIDEOS_MOVIES]  = "Películas",
    [AURA_STR_VIDEOS_TVSHOWS] = "Programas de TV",
    [AURA_STR_VIDEOS_CLIPS]   = "Videoclips",
    [AURA_STR_VIDEOS_ALL]     = "Todos los videos",
    [AURA_STR_PHOTOS_ALL]     = "Todas las fotos",
    [AURA_STR_SETTINGS_COPYRIGHT] = "Avisos legales",
    [AURA_STR_COPYRIGHT_BODY] = "Aura es un firmware CONCEPTUAL para iPod Classic, construido sobre Rockbox.\n\nRockbox\nEste firmware deriva del proyecto Rockbox y se distribuye bajo la Licencia Publica General de GNU (GPL v2). El nucleo, los controladores, el sistema de archivos, los codecs y el motor de reproduccion son obra del equipo de Rockbox y de sus colaboradores, a quienes corresponde todo el credito por ese trabajo.\n\nApple\niPod, iPod Classic, iTunes, Finder, SF Symbols y Apple son marcas registradas de Apple Inc. Aura no esta afiliado, patrocinado ni respaldado por Apple Inc. Los simbolos SF se renderizan desde el sistema operativo del equipo donde se compila y siguen sujetos a la licencia de Apple. Este proyecto es un ejercicio de diseno inspirado en el iPod, no un producto de Apple ni un sustituto de su software.\n\nDistribucion\nEste firmware es meramente conceptual. Esta PROHIBIDA su distribucion y ESTRICTAMENTE PROHIBIDA su venta. Si se comparte, es unicamente con fines didacticos y de investigacion.\n\nCreditos\nDiseno: Ricardo Gomez (Ricolinos).\nImplementacion del codigo: Claude, de Anthropic, bajo la direccion de diseno de Ricardo Gomez.\n\nSin garantia de ningun tipo, expresa o implicita.",
    [AURA_STR_WC_LOCAL]  = "Hora local",
    [AURA_STR_WC_ADD]    = "Añadir",
    [AURA_STR_WC_EDIT]   = "Editar",
    [AURA_STR_WC_DELETE] = "Eliminar",
    [AURA_STR_SETTINGS_AUDIOBOOKS]  = "Audiolibros",
    [AURA_STR_SETTINGS_VOLUME_NORM] = "Ajuste volumen",
    [AURA_STR_SETTINGS_SORT_BY]     = "Ordenar por",
    [AURA_STR_SETTINGS_MUSICMENU]   = "Menú Música",
    [AURA_STR_SPEED_SLOW]           = "Lenta",
    [AURA_STR_SPEED_NORMAL]         = "Normal",
    [AURA_STR_SPEED_FAST]           = "Rápida",
    [AURA_STR_AUDIOBOOKS_BODY]      = "¿Deseas ajustar la velocidad de reproducción de los audiolibros?\n\nLa velocidad de reproducción no afectará al tono de voz de la reproducción de los audiolibros.",
    [AURA_STR_SORT_FIRSTNAME]       = "Nombre",
    [AURA_STR_SORT_LASTNAME]        = "Apellido",
    [AURA_STR_NOTES_BODY]           = "Visualización y creación de notas\n\nPara ver archivos de texto aquí, activa la opción de usar el iPod como disco en iTunes y, a continuación, arrastra los archivos de texto a la carpeta Notes del iPod.\n\nPara más información, consulta el Manual de funciones del iPod o visita www.apple.com/es/support/ipod.",
    [AURA_STR_GAME_IQUIZ]           = "iQuiz",
    [AURA_STR_GAME_KLONDIKE]        = "Klondike",
    [AURA_STR_GAME_VORTEX]          = "Vortex",
    [AURA_STR_CAL_NO_EVENTS] = "No hay eventos este día",
    [AURA_STR_LOCK_SET] = "Introduce una clave",
    [AURA_STR_LOCK_CONFIRM] = "Confirma la clave",
    [AURA_STR_LOCK_ENTER] = "iPod bloqueado. Introduce tu clave",
    [AURA_STR_ALARM_NEW]    = "Alarma nueva",
    [AURA_STR_ALARM_HOUR]   = "Ajustando la hora",
    [AURA_STR_ALARM_MINUTE] = "Ajustando los minutos",
    [AURA_STR_SETTINGS_DATETIME]    = "Fecha y hora",
    [AURA_STR_SETTINGS_TIMEZONE]    = "Zona horaria",
    [AURA_STR_SETTINGS_CLOCK24]     = "Reloj 24 horas",
    [AURA_STR_SETTINGS_CLOCK_TITLE] = "Hora en el título",
    [AURA_STR_SETTINGS_DATE] = "Fecha",
    [AURA_STR_SETTINGS_TIME] = "Hora",
    [AURA_STR_PRECACHE_ART]  = "Preparando carátulas",
    [AURA_STR_SETTINGS_POWEROFF]   = "Apagado del iPod",
    [AURA_STR_POWEROFF_10MIN]      = "Después de 10 min.",
    [AURA_STR_POWEROFF_20MIN]      = "Después de 20 min.",
    [AURA_STR_POWEROFF_1HOUR]      = "Después de 1 hora",
    [AURA_STR_SCREENLOCK_DISABLE_TITLE] = "Desactivar bloqueo",
    [AURA_STR_SCREENLOCK_DISABLE_BODY]  = "Se borrará la clave guardada. Para volver a activar el bloqueo habrá que configurar una clave nueva.",

    [AURA_STR_MUSIC_EMPTY_ARTISTS]    = "No hay artistas",
    [AURA_STR_MUSIC_EMPTY_ALBUMS]     = "No hay álbumes",
    [AURA_STR_MUSIC_EMPTY_SONGS]      = "No hay canciones",
    [AURA_STR_MUSIC_EMPTY_PLAYLISTS]  = "No hay listas",
    [AURA_STR_MUSIC_EMPTY_GENRES]     = "No hay géneros",
    [AURA_STR_MUSIC_EMPTY_COMPOSERS]  = "No hay compositores",
    [AURA_STR_MUSIC_EMPTY_AUDIOBOOKS] = "No hay audiolibros",
    [AURA_STR_VIDEOS_EMPTY_MOVIES]    = "No hay películas",
    [AURA_STR_VIDEOS_EMPTY_TVSHOWS]   = "No hay series",
    [AURA_STR_VIDEOS_EMPTY_CLIPS]     = "No hay videoclips",

    [AURA_STR_TOGGLE_ON]              = "Activado",
    [AURA_STR_TOGGLE_OFF]             = "Desactivado",

    [AURA_STR_REPEAT_ROW_TOP]         = "Repetir",
    [AURA_STR_REPEAT_SUMMARY_ALL]     = "Repetir todo",
    [AURA_STR_REPEAT_SUMMARY_ONE]     = "Repetir una",

    [AURA_STR_ABOUT_MY_IPOD]          = "Mi iPod",
    [AURA_STR_ABOUT_OTHER]            = "Otros",
    [AURA_STR_ABOUT_SYSTEM]           = "Sistema",
};

static const char *const strings_en[AURA_STR_COUNT] = {
    [AURA_STR_MUSIC]              = "Music",
    [AURA_STR_VIDEOS]             = "Videos",
    [AURA_STR_PHOTOS]             = "Photos",
    [AURA_STR_NOWPLAYING]         = "Now Playing",
    [AURA_STR_SETTINGS]           = "Settings",

    [AURA_STR_SETTINGS_THEME]       = "Theme",
    [AURA_STR_SETTINGS_ANIMATIONS]  = "Animations",
    [AURA_STR_SETTINGS_GRAPHICS]    = "Graphics",
    [AURA_STR_SETTINGS_EQ]          = "Equalizer",
    [AURA_STR_SETTINGS_BRIGHTNESS]  = "Brightness",
    [AURA_STR_SETTINGS_LANGUAGE]    = "Language",
    [AURA_STR_SETTINGS_ABOUT]       = "About",
    [AURA_STR_SETTINGS_SHUFFLE]     = "Shuffle",
    [AURA_STR_SETTINGS_REPEAT]      = "Repeat",

    [AURA_STR_REPEAT_OFF]           = "Off",
    [AURA_STR_REPEAT_ALL]           = "All",
    [AURA_STR_REPEAT_ONE]           = "One",

    [AURA_STR_SETTINGS_BACKLIGHT]    = "Backlight timer",
    [AURA_STR_SETTINGS_SLEEPTIMER]   = "Sleep timer",
    [AURA_STR_SETTINGS_VOLUME_LIMIT] = "Volume limit",
    [AURA_STR_SETTINGS_CLICKER]      = "Clicker",
    [AURA_STR_SETTINGS_MAINMENU]     = "Main menu",
    [AURA_STR_SETTINGS_RESET]        = "Reset settings",

    [AURA_STR_TIMEOUT_OFF]          = "Off",
    [AURA_STR_TIMEOUT_ALWAYS]       = "Always",

    [AURA_STR_MAINMENU_RESTORE]     = "Restore main menu",

    [AURA_STR_RESET_CONFIRM_TITLE]  = "Reset settings",
    [AURA_STR_RESET_CONFIRM_BODY]   = "This resets every setting back to its default.",
    [AURA_STR_RESET_DONE]           = "Settings reset",

    [AURA_STR_THEME_LIGHT]        = "Light",
    [AURA_STR_THEME_DARK]         = "Dark",

    [AURA_STR_ANIM_NONE]          = "None",
    [AURA_STR_ANIM_MINIMAL]       = "Minimal",
    [AURA_STR_ANIM_ALL]           = "All",

    [AURA_STR_GFX_NONE]           = "None",
    [AURA_STR_GFX_MINIMAL]        = "Minimal",
    [AURA_STR_GFX_ALL]            = "All",


    [AURA_STR_LANG_ES]            = "Spanish",
    [AURA_STR_LANG_EN]            = "English",

    [AURA_STR_ABOUT_BUILT_ON]     = "Built on Rockbox",
    [AURA_STR_ABOUT_MUSIC]        = "Music",
    [AURA_STR_ABOUT_VIDEOS]       = "Video",
    [AURA_STR_ABOUT_PHOTOS]       = "Photos",
    [AURA_STR_ABOUT_PLAYLISTS]    = "Playlists",
    [AURA_STR_ABOUT_NO_SYNC]      = "You haven't synced with Aura Studio yet.",

    [AURA_STR_EMPTY_MUSIC]        = "No music yet",
    [AURA_STR_EMPTY_VIDEOS]       = "No videos yet",
    [AURA_STR_EMPTY_PHOTOS]       = "No photos yet",
    [AURA_STR_NOTHING_PLAYING]    = "Nothing playing",

    [AURA_STR_MUSIC_ARTISTS]      = "Artists",
    [AURA_STR_MUSIC_ALBUMS]       = "Albums",
    [AURA_STR_MUSIC_SONGS]        = "Songs",
    [AURA_STR_MUSIC_PLAYLISTS]    = "Playlists",
    [AURA_STR_MUSIC_GENRES]       = "Genres",
    [AURA_STR_DB_NOT_READY]       = "Preparing your library...",
    [AURA_STR_EMPTY_LIST]         = "No results",
    [AURA_STR_UNSUPPORTED_FORMAT] = "Unsupported format",

    [AURA_STR_YES]                = "Yes",
    [AURA_STR_NO]                 = "No",

    [AURA_STR_ABOUT_STORAGE]      = "Storage",
    [AURA_STR_PLAYLIST_PICK]      = "Turn the wheel to choose",

    [AURA_STR_SETTINGS_ACCENT]    = "Accent color",
    [AURA_STR_ACCENT_PINK]        = "Pink",
    [AURA_STR_ACCENT_RED]         = "Red",
    [AURA_STR_ACCENT_ORANGE]      = "Orange",
    [AURA_STR_ACCENT_GREEN]       = "Green",
    [AURA_STR_ACCENT_BLUE]        = "Blue",
    [AURA_STR_ACCENT_PURPLE]      = "Purple",
    [AURA_STR_SETTINGS_LEFT_PANEL_SHADOW] = "Show shadows",
    [AURA_STR_MUSIC_COVERFLOW]    = "Cover Flow",
    [AURA_STR_UNKNOWN_ALBUM]      = "Unknown album",
    [AURA_STR_UNKNOWN_ARTIST]     = "Unknown artist",
    [AURA_STR_UNKNOWN_GENRE]      = "Unknown genre",
    [AURA_STR_UNKNOWN_TITLE]      = "Untitled",
    [AURA_STR_MUSIC_COMPOSERS]    = "Composers",
    [AURA_STR_MUSIC_COMPILATIONS] = "Compilations",
    [AURA_STR_MUSIC_AUDIOBOOKS]   = "Audiobooks",
    [AURA_STR_MUSIC_SEARCH]       = "Search",
    [AURA_STR_ALL]                = "All",
    [AURA_STR_EXTRAS]             = "Extras",
    [AURA_STR_SHUFFLE_SONGS]      = "Shuffle Songs",
    [AURA_STR_EXTRAS_CLOCKS]      = "World Clock",
    [AURA_STR_EXTRAS_CALENDAR]    = "Calendars",
    [AURA_STR_EXTRAS_CONTACTS]    = "Contacts",
    [AURA_STR_EXTRAS_ALARMS]      = "Alarms",
    [AURA_STR_EXTRAS_GAMES]       = "Games",
    [AURA_STR_EXTRAS_NOTES]       = "Notes",
    [AURA_STR_SETTINGS_SCREENLOCK] = "Screen Lock",
    [AURA_STR_EXTRAS_STOPWATCH]   = "Stopwatch",
    [AURA_STR_EMPTY_GENERIC]      = "Nothing here yet",
    [AURA_STR_SETTINGS_SHOW_ICONS] = "Show icons",
    [AURA_STR_EQ_OFF] = "Off",
    [AURA_STR_EQ_ACOUSTIC] = "Acoustic",
    [AURA_STR_EQ_BASS_BOOST] = "Bass Booster",
    [AURA_STR_EQ_BASS_RED] = "Bass Reducer",
    [AURA_STR_EQ_CLASSICAL] = "Classical",
    [AURA_STR_EQ_DANCE] = "Dance",
    [AURA_STR_EQ_DEEP] = "Deep",
    [AURA_STR_EQ_ELECTRONIC] = "Electronic",
    [AURA_STR_EQ_FLAT] = "Flat",
    [AURA_STR_EQ_HIPHOP] = "Hip-Hop",
    [AURA_STR_EQ_JAZZ] = "Jazz",
    [AURA_STR_EQ_LATIN] = "Latin",
    [AURA_STR_EQ_LOUDNESS] = "Loudness",
    [AURA_STR_EQ_LOUNGE] = "Lounge",
    [AURA_STR_EQ_PIANO] = "Piano",
    [AURA_STR_EQ_POP] = "Pop",
    [AURA_STR_EQ_RNB] = "R&B",
    [AURA_STR_EQ_ROCK] = "Rock",
    [AURA_STR_EQ_SMALLSPK] = "Small Speakers",
    [AURA_STR_EQ_SPOKEN] = "Spoken Word",
    [AURA_STR_EQ_TREBLE_RED] = "Treble Reducer",
    [AURA_STR_EQ_VOCAL_BOOST] = "Vocal Booster",
    [AURA_STR_LANG_DA] = "Dansk",
    [AURA_STR_LANG_DE] = "Deutsch",
    [AURA_STR_LANG_FR] = "Français",
    [AURA_STR_LANG_IT] = "Italiano",
    [AURA_STR_LANG_NL] = "Nederlands",
    [AURA_STR_LANG_NO] = "Norsk",
    [AURA_STR_LANG_PT] = "Português",
    [AURA_STR_LANG_FI] = "Suomi",
    [AURA_STR_LANG_SV] = "Svenska",
    [AURA_STR_LANG_JA] = "Japanese",
    [AURA_STR_LANG_ZH] = "Chinese",
    [AURA_STR_LANG_KO] = "Korean",
    [AURA_STR_LANG_RU] = "Russian",
    [AURA_STR_VIDEOS_MOVIES]  = "Movies",
    [AURA_STR_VIDEOS_TVSHOWS] = "TV Shows",
    [AURA_STR_VIDEOS_CLIPS]   = "Music Videos",
    [AURA_STR_VIDEOS_ALL]     = "All Videos",
    [AURA_STR_PHOTOS_ALL]     = "All Photos",
    [AURA_STR_SETTINGS_COPYRIGHT] = "Legal",
    [AURA_STR_COPYRIGHT_BODY] = "Aura is a CONCEPTUAL firmware for the iPod Classic, built on Rockbox.\n\nRockbox\nThis firmware derives from the Rockbox project and is distributed under the GNU General Public License (GPL v2). The kernel, drivers, file system, codecs and playback engine are the work of the Rockbox team and its contributors, who deserve full credit for it.\n\nApple\niPod, iPod Classic, iTunes, Finder, SF Symbols and Apple are registered trademarks of Apple Inc. Aura is not affiliated with, sponsored by or endorsed by Apple Inc. SF Symbols are rendered from the operating system of the machine where this is built and remain subject to Apple's license. This project is a design exercise inspired by the iPod, not an Apple product nor a replacement for its software.\n\nDistribution\nThis firmware is purely conceptual. Its distribution is PROHIBITED and its sale is STRICTLY PROHIBITED. If shared, it is solely for educational and research purposes.\n\nCredits\nDesign: Ricardo Gomez (Ricolinos).\nCode implementation: Claude, by Anthropic, under the design direction of Ricardo Gomez.\n\nNo warranty of any kind, express or implied.",
    [AURA_STR_WC_LOCAL]  = "Local Time",
    [AURA_STR_WC_ADD]    = "Add",
    [AURA_STR_WC_EDIT]   = "Edit",
    [AURA_STR_WC_DELETE] = "Delete",
    [AURA_STR_SETTINGS_AUDIOBOOKS]  = "Audiobooks",
    [AURA_STR_SETTINGS_VOLUME_NORM] = "Sound Check",
    [AURA_STR_SETTINGS_SORT_BY]     = "Sort By",
    [AURA_STR_SETTINGS_MUSICMENU]   = "Music Menu",
    [AURA_STR_SPEED_SLOW]           = "Slower",
    [AURA_STR_SPEED_NORMAL]         = "Normal",
    [AURA_STR_SPEED_FAST]           = "Faster",
    [AURA_STR_AUDIOBOOKS_BODY]      = "Do you want to adjust the playback speed of audiobooks?\n\nPlayback speed will not affect the pitch of the voice in audiobook playback.",
    [AURA_STR_SORT_FIRSTNAME]       = "First Name",
    [AURA_STR_SORT_LASTNAME]        = "Last Name",
    [AURA_STR_NOTES_BODY]           = "Viewing and creating notes\n\nTo view text files here, enable the option to use your iPod as a disk in iTunes, then drag the text files to the Notes folder on your iPod.\n\nFor more information, see the iPod Features Guide or visit www.apple.com/support/ipod.",
    [AURA_STR_GAME_IQUIZ]           = "iQuiz",
    [AURA_STR_GAME_KLONDIKE]        = "Klondike",
    [AURA_STR_GAME_VORTEX]          = "Vortex",
    [AURA_STR_CAL_NO_EVENTS] = "No events on this day",
    [AURA_STR_LOCK_SET] = "Enter a passcode",
    [AURA_STR_LOCK_CONFIRM] = "Confirm the passcode",
    [AURA_STR_LOCK_ENTER] = "iPod locked. Enter your passcode",
    [AURA_STR_ALARM_NEW]    = "New Alarm",
    [AURA_STR_ALARM_HOUR]   = "Setting hour",
    [AURA_STR_ALARM_MINUTE] = "Setting minutes",
    [AURA_STR_SETTINGS_DATETIME]    = "Date & Time",
    [AURA_STR_SETTINGS_TIMEZONE]    = "Time Zone",
    [AURA_STR_SETTINGS_CLOCK24]     = "24 Hour Clock",
    [AURA_STR_SETTINGS_CLOCK_TITLE] = "Time in Title",
    [AURA_STR_SETTINGS_DATE] = "Date",
    [AURA_STR_SETTINGS_TIME] = "Time",
    [AURA_STR_PRECACHE_ART]  = "Preparing artwork",
    [AURA_STR_SETTINGS_POWEROFF]   = "iPod Auto-Off",
    [AURA_STR_POWEROFF_10MIN]      = "After 10 min.",
    [AURA_STR_POWEROFF_20MIN]      = "After 20 min.",
    [AURA_STR_POWEROFF_1HOUR]      = "After 1 hour",
    [AURA_STR_SCREENLOCK_DISABLE_TITLE] = "Turn Off Screen Lock",
    [AURA_STR_SCREENLOCK_DISABLE_BODY]  = "The saved passcode will be deleted. To turn the lock back on you'll need to set a new passcode.",

    [AURA_STR_MUSIC_EMPTY_ARTISTS]    = "No artists",
    [AURA_STR_MUSIC_EMPTY_ALBUMS]     = "No albums",
    [AURA_STR_MUSIC_EMPTY_SONGS]      = "No songs",
    [AURA_STR_MUSIC_EMPTY_PLAYLISTS]  = "No playlists",
    [AURA_STR_MUSIC_EMPTY_GENRES]     = "No genres",
    [AURA_STR_MUSIC_EMPTY_COMPOSERS]  = "No composers",
    [AURA_STR_MUSIC_EMPTY_AUDIOBOOKS] = "No audiobooks",
    [AURA_STR_VIDEOS_EMPTY_MOVIES]    = "No movies",
    [AURA_STR_VIDEOS_EMPTY_TVSHOWS]   = "No TV shows",
    [AURA_STR_VIDEOS_EMPTY_CLIPS]     = "No video clips",

    [AURA_STR_TOGGLE_ON]              = "On",
    [AURA_STR_TOGGLE_OFF]             = "Off",

    [AURA_STR_REPEAT_ROW_TOP]         = "Repeat",
    [AURA_STR_REPEAT_SUMMARY_ALL]     = "Repeat All",
    [AURA_STR_REPEAT_SUMMARY_ONE]     = "Repeat One",

    [AURA_STR_ABOUT_MY_IPOD]          = "My iPod",
    [AURA_STR_ABOUT_OTHER]            = "Other",
    [AURA_STR_ABOUT_SYSTEM]           = "System",
};

const char *aura_str(aura_str_id_t id)
{
    if (id < 0 || id >= AURA_STR_COUNT)
        return "";

    const char *s = (aura_settings.language == AURA_LANG_EN)
                        ? strings_en[id]
                        : strings_es[id];
    return s ? s : "";
}
